# Generated by Django 6.0.2 on 2026-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_title_az', models.CharField(max_length=255, null=True)),
                ('hero_title_en', models.CharField(max_length=255, null=True)),
                ('hero_title_ru', models.CharField(max_length=255, null=True)),
                ('hero_description', models.TextField()),
                ('hero_description_az', models.TextField(null=True)),
                ('hero_description_en', models.TextField(null=True)),
                ('hero_description_ru', models.TextField(null=True)),
                ('hero_image', models.ImageField(upload_to='about/')),
                ('vision_title', models.CharField(max_length=255)),
                ('vision_title_az', models.CharField(max_length=255, null=True)),
                ('vision_title_en', models.CharField(max_length=255, null=True)),
                ('vision_title_ru', models.CharField(max_length=255, null=True)),
                ('vision_description', models.TextField()),
                ('vision_description_az', models.TextField(null=True)),
                ('vision_description_en', models.TextField(null=True)),
                ('vision_description_ru', models.TextField(null=True)),
                ('mission_title', models.CharField(max_length=255)),
                ('mission_title_az', models.CharField(max_length=255, null=True)),
                ('mission_title_en', models.CharField(max_length=255, null=True)),
                ('mission_title_ru', models.CharField(max_length=255, null=True)),
                ('mission_description', models.TextField()),
                ('mission_description_az', models.TextField(null=True)),
                ('mission_description_en', models.TextField(null=True)),
                ('mission_description_ru', models.TextField(null=True)),
                ('quote_text', models.TextField()),
                ('quote_text_az', models.TextField(null=True)),
                ('quote_text_en', models.TextField(null=True)),
                ('quote_text_ru', models.TextField(null=True)),
                ('quote_author', models.CharField(max_length=100)),
                ('quote_author_az', models.CharField(max_length=100, null=True)),
                ('quote_author_en', models.CharField(max_length=100, null=True)),
                ('quote_author_ru', models.CharField(max_length=100, null=True)),
                ('quote_role', models.CharField(max_length=100)),
                ('quote_role_az', models.CharField(max_length=100, null=True)),
                ('quote_role_en', models.CharField(max_length=100, null=True)),
                ('quote_role_ru', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Haqqımızda Məzmun',
                'verbose_name_plural': 'Haqqımızda Məzmun',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('label_az', models.CharField(max_length=100, null=True)),
                ('label_en', models.CharField(max_length=100, null=True)),
                ('label_ru', models.CharField(max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Haqqımızda Statistika',
                'verbose_name_plural': 'Haqqımızda Statistikaları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_az', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Üstünlük',
                'verbose_name_plural': 'Üstünlüklərimiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_az', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('question_ru', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_az', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
    ]
