# Generated by Django 6.0.2 on 2026-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutcontent_id_alter_aboutstat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='hero_description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='hero_title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='quote_author_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='quote_role_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='quote_text_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutstat',
            name='label_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
