# Generated by Django 6.0.2 on 2026-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(verbose_name='Qısa xülasə')),
                ('excerpt_az', models.TextField(null=True, verbose_name='Qısa xülasə')),
                ('excerpt_en', models.TextField(null=True, verbose_name='Qısa xülasə')),
                ('excerpt_ru', models.TextField(null=True, verbose_name='Qısa xülasə')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('content_az', models.TextField(null=True, verbose_name='Məzmun')),
                ('content_en', models.TextField(null=True, verbose_name='Məzmun')),
                ('content_ru', models.TextField(null=True, verbose_name='Məzmun')),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='Şəkil')),
                ('author', models.CharField(default='Neyman Admin', max_length=100, verbose_name='Müəllif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarix')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ana səhifədə göstər?')),
            ],
            options={
                'verbose_name': 'Xəbər / Bloq',
                'verbose_name_plural': 'Xəbərlər',
                'ordering': ['-created_at'],
            },
        ),
    ]
