# Generated by Django 6.0.2 on 2026-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='blog',
            name='excerpt_tr',
            field=models.TextField(null=True, verbose_name='Qısa xülasə'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
    ]
