# Generated by Django 6.0.2 on 2026-07-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_content_tr_blog_excerpt_tr_blog_title_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug_az',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_tr',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
