# Generated by Django 6.0.2 on 2026-03-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Layihə adı')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='Layihə adı')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Layihə adı')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Layihə adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(max_length=100, verbose_name='Kateqoriya')),
                ('category_az', models.CharField(max_length=100, null=True, verbose_name='Kateqoriya')),
                ('category_en', models.CharField(max_length=100, null=True, verbose_name='Kateqoriya')),
                ('category_ru', models.CharField(max_length=100, null=True, verbose_name='Kateqoriya')),
                ('description', models.TextField(verbose_name='Qısa təsvir')),
                ('description_az', models.TextField(null=True, verbose_name='Qısa təsvir')),
                ('description_en', models.TextField(null=True, verbose_name='Qısa təsvir')),
                ('description_ru', models.TextField(null=True, verbose_name='Qısa təsvir')),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/', verbose_name='Əsas şəkil')),
                ('content', models.TextField(blank=True, verbose_name='Layihə haqqında ətraflı')),
                ('content_az', models.TextField(blank=True, null=True, verbose_name='Layihə haqqında ətraflı')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Layihə haqqında ətraflı')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Layihə haqqında ətraflı')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Müştəri')),
                ('client_name_az', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müştəri')),
                ('client_name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müştəri')),
                ('client_name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müştəri')),
                ('completion_date', models.CharField(blank=True, max_length=100, verbose_name='Tamamlanma tarixi')),
                ('website_url', models.URLField(blank=True, verbose_name='Vebsayt linki')),
                ('testimonial_quote', models.TextField(blank=True, verbose_name='Müştəri rəyi')),
                ('testimonial_quote_az', models.TextField(blank=True, null=True, verbose_name='Müştəri rəyi')),
                ('testimonial_quote_en', models.TextField(blank=True, null=True, verbose_name='Müştəri rəyi')),
                ('testimonial_quote_ru', models.TextField(blank=True, null=True, verbose_name='Müştəri rəyi')),
                ('testimonial_author', models.CharField(blank=True, max_length=200, verbose_name='Rəy müəllifi')),
                ('testimonial_author_az', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rəy müəllifi')),
                ('testimonial_author_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rəy müəllifi')),
                ('testimonial_author_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rəy müəllifi')),
                ('testimonial_role', models.CharField(blank=True, max_length=200, verbose_name='Müəllifin vəzifəsi')),
                ('testimonial_role_az', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müəllifin vəzifəsi')),
                ('testimonial_role_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müəllifin vəzifəsi')),
                ('testimonial_role_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müəllifin vəzifəsi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ana səhifədə göstər?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Layihə',
                'verbose_name_plural': 'Layihələr',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Layihə Şəkli',
                'verbose_name_plural': 'Layihə Qalereyası',
            },
        ),
    ]
