# Generated by Django 6.0.2 on 2026-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, verbose_name='Problem'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_az',
            field=models.TextField(blank=True, null=True, verbose_name='Problem'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_en',
            field=models.TextField(blank=True, null=True, verbose_name='Problem'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Problem'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Həll'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_az',
            field=models.TextField(blank=True, null=True, verbose_name='Həll'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_en',
            field=models.TextField(blank=True, null=True, verbose_name='Həll'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Həll'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, help_text='Məs: React, Django, AWS', verbose_name='Texnologiyalar (vergüllə ayrılmış)'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_az',
            field=models.TextField(blank=True, help_text='Məs: React, Django, AWS', null=True, verbose_name='Texnologiyalar (vergüllə ayrılmış)'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_en',
            field=models.TextField(blank=True, help_text='Məs: React, Django, AWS', null=True, verbose_name='Texnologiyalar (vergüllə ayrılmış)'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_ru',
            field=models.TextField(blank=True, help_text='Məs: React, Django, AWS', null=True, verbose_name='Texnologiyalar (vergüllə ayrılmış)'),
        ),
    ]
