# Generated by Django 6.0.2 on 2026-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_id_alter_projectimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Kateqoriya'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Müştəri'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Layihə haqqında ətraflı'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Qısa təsvir'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Problem'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Həll'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_tr',
            field=models.TextField(blank=True, help_text='Məs: React, Django, AWS', null=True, verbose_name='Texnologiyalar (vergüllə ayrılmış)'),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_author_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rəy müəllifi'),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_quote_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Müştəri rəyi'),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_role_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Müəllifin vəzifəsi'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Layihə adı'),
        ),
    ]
