# Generated by Django 6.0.2 on 2026-07-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features_tr',
        ),
        migrations.AddField(
            model_name='product',
            name='cta_link',
            field=models.CharField(default='#demo', max_length=200, verbose_name='Əsas Düymə Linki'),
        ),
        migrations.AddField(
            model_name='product',
            name='cta_text',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, verbose_name='Əsas Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='cta_text_az',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, null=True, verbose_name='Əsas Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='cta_text_en',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, null=True, verbose_name='Əsas Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='cta_text_ru',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, null=True, verbose_name='Əsas Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='cta_text_tr',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, null=True, verbose_name='Əsas Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='font_family',
            field=models.CharField(default='Poppins', help_text='Məsələn: Poppins, Inter, Roboto', max_length=50, verbose_name='Şrift (Font Family)'),
        ),
        migrations.AddField(
            model_name='product',
            name='navbar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/logos/', verbose_name='Xüsusi Navbar Logosu'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_link',
            field=models.CharField(default='#pricing', max_length=200, verbose_name='İkinci Düymə Linki'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_text',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, verbose_name='İkinci Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_text_az',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, null=True, verbose_name='İkinci Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_text_en',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, null=True, verbose_name='İkinci Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_text_ru',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, null=True, verbose_name='İkinci Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_cta_text_tr',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, null=True, verbose_name='İkinci Düymə Mətni'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq (Hero üçün)'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_az',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq (Hero üçün)'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq (Hero üçün)'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq (Hero üçün)'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq (Hero üçün)'),
        ),
        migrations.AddField(
            model_name='product',
            name='theme_color',
            field=models.CharField(default='blue', help_text='Məsələn: blue, indigo, #2563eb', max_length=50, verbose_name='Mövzu Rəngi (Hex və ya sinif)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Təsvir (Hero üçün)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Təsvir (Hero üçün)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Təsvir (Hero üçün)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Təsvir (Hero üçün)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Təsvir (Hero üçün)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Şəkil / Qrafika'),
        ),
        migrations.CreateModel(
            name='ProductBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Üstünlük başlığı')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='Üstünlük başlığı')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Üstünlük başlığı')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Üstünlük başlığı')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Üstünlük başlığı')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('description_az', models.TextField(null=True, verbose_name='Təsvir')),
                ('description_en', models.TextField(null=True, verbose_name='Təsvir')),
                ('description_ru', models.TextField(null=True, verbose_name='Təsvir')),
                ('description_tr', models.TextField(null=True, verbose_name='Təsvir')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='İkon (Məs: FaCheckCircle)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='products.product')),
            ],
            options={
                'verbose_name': 'Üstünlük (Benefit)',
                'verbose_name_plural': 'Üstünlüklər (Benefits)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Xüsusiyyət başlığı')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='Xüsusiyyət başlığı')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Xüsusiyyət başlığı')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Xüsusiyyət başlığı')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Xüsusiyyət başlığı')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('description_az', models.TextField(null=True, verbose_name='Təsvir')),
                ('description_en', models.TextField(null=True, verbose_name='Təsvir')),
                ('description_ru', models.TextField(null=True, verbose_name='Təsvir')),
                ('description_tr', models.TextField(null=True, verbose_name='Təsvir')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='İkon (Məsələn: FaBolt, FaShieldAlt)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': 'Xüsusiyyət',
                'verbose_name_plural': 'Xüsusiyyətlər',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductNavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Link Mətni')),
                ('title_az', models.CharField(max_length=100, null=True, verbose_name='Link Mətni')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Link Mətni')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Link Mətni')),
                ('title_tr', models.CharField(max_length=100, null=True, verbose_name='Link Mətni')),
                ('url', models.CharField(help_text='Məsələn: #features, #pricing', max_length=200, verbose_name='Link (URL və ya ID)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_links', to='products.product')),
            ],
            options={
                'verbose_name': 'Navbar Linki',
                'verbose_name_plural': 'Navbar Linkləri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('name_az', models.CharField(max_length=100, null=True, verbose_name='Paket Adı')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Paket Adı')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Paket Adı')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Paket Adı')),
                ('price', models.CharField(help_text='Məs: 99₼, Xüsusi', max_length=50, verbose_name='Qiymət')),
                ('period', models.CharField(blank=True, help_text='Məs: /aylıq, /illik', max_length=50, verbose_name='Müddət')),
                ('period_az', models.CharField(blank=True, help_text='Məs: /aylıq, /illik', max_length=50, null=True, verbose_name='Müddət')),
                ('period_en', models.CharField(blank=True, help_text='Məs: /aylıq, /illik', max_length=50, null=True, verbose_name='Müddət')),
                ('period_ru', models.CharField(blank=True, help_text='Məs: /aylıq, /illik', max_length=50, null=True, verbose_name='Müddət')),
                ('period_tr', models.CharField(blank=True, help_text='Məs: /aylıq, /illik', max_length=50, null=True, verbose_name='Müddət')),
                ('description', models.CharField(max_length=200, verbose_name='Qısa Təsvir')),
                ('description_az', models.CharField(max_length=200, null=True, verbose_name='Qısa Təsvir')),
                ('description_en', models.CharField(max_length=200, null=True, verbose_name='Qısa Təsvir')),
                ('description_ru', models.CharField(max_length=200, null=True, verbose_name='Qısa Təsvir')),
                ('description_tr', models.CharField(max_length=200, null=True, verbose_name='Qısa Təsvir')),
                ('features', models.TextField(verbose_name='Paket Xüsusiyyətləri (Hər sətirə bir dənə)')),
                ('features_az', models.TextField(null=True, verbose_name='Paket Xüsusiyyətləri (Hər sətirə bir dənə)')),
                ('features_en', models.TextField(null=True, verbose_name='Paket Xüsusiyyətləri (Hər sətirə bir dənə)')),
                ('features_ru', models.TextField(null=True, verbose_name='Paket Xüsusiyyətləri (Hər sətirə bir dənə)')),
                ('features_tr', models.TextField(null=True, verbose_name='Paket Xüsusiyyətləri (Hər sətirə bir dənə)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Ən Çox Seçilən (Popular)?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='products.product')),
            ],
            options={
                'verbose_name': 'Qiymət Paketi',
                'verbose_name_plural': 'Qiymət Paketləri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Məs: Aktiv İstifadəçi', max_length=100, verbose_name='Statistika başlığı')),
                ('label_az', models.CharField(help_text='Məs: Aktiv İstifadəçi', max_length=100, null=True, verbose_name='Statistika başlığı')),
                ('label_en', models.CharField(help_text='Məs: Aktiv İstifadəçi', max_length=100, null=True, verbose_name='Statistika başlığı')),
                ('label_ru', models.CharField(help_text='Məs: Aktiv İstifadəçi', max_length=100, null=True, verbose_name='Statistika başlığı')),
                ('label_tr', models.CharField(help_text='Məs: Aktiv İstifadəçi', max_length=100, null=True, verbose_name='Statistika başlığı')),
                ('value', models.CharField(help_text='Məs: 10K+', max_length=100, verbose_name='Dəyər')),
                ('value_az', models.CharField(help_text='Məs: 10K+', max_length=100, null=True, verbose_name='Dəyər')),
                ('value_en', models.CharField(help_text='Məs: 10K+', max_length=100, null=True, verbose_name='Dəyər')),
                ('value_ru', models.CharField(help_text='Məs: 10K+', max_length=100, null=True, verbose_name='Dəyər')),
                ('value_tr', models.CharField(help_text='Məs: 10K+', max_length=100, null=True, verbose_name='Dəyər')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='products.product')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['order'],
            },
        ),
    ]
