# Generated by Django 6.0.2 on 2026-07-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_features_remove_product_features_az_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbenefit',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='productnavbarlink',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='productpricing',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='productstat',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='productnavbarlink',
            name='title',
        ),
        migrations.RemoveField(
            model_name='productnavbarlink',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='productnavbarlink',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='productnavbarlink',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='productnavbarlink',
            name='title_tr',
        ),
        migrations.RemoveField(
            model_name='productnavbarlink',
            name='url',
        ),
        migrations.AddField(
            model_name='productnavbarlink',
            name='href',
            field=models.CharField(default='#', max_length=200, verbose_name='Link (Məs: #features)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productnavbarlink',
            name='label',
            field=models.CharField(default='Link', max_length=100, verbose_name='Menyu Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productnavbarlink',
            name='label_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Menyu Adı'),
        ),
        migrations.AddField(
            model_name='productnavbarlink',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Menyu Adı'),
        ),
        migrations.AddField(
            model_name='productnavbarlink',
            name='label_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Menyu Adı'),
        ),
        migrations.AddField(
            model_name='productnavbarlink',
            name='label_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Menyu Adı'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='price_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Qiymət (Məs: 99₼)'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='price_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Qiymət (Məs: 99₼)'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='price_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Qiymət (Məs: 99₼)'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='price_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='Qiymət (Məs: 99₼)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cta_link',
            field=models.CharField(default='#demo', max_length=200, verbose_name='Əsas düymə linki'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cta_text',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, verbose_name='Əsas düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cta_text_az',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, null=True, verbose_name='Əsas düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cta_text_en',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, null=True, verbose_name='Əsas düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cta_text_ru',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, null=True, verbose_name='Əsas düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cta_text_tr',
            field=models.CharField(default='Demo Sifariş Et', max_length=100, null=True, verbose_name='Əsas düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='font_family',
            field=models.CharField(default='Inter', max_length=50, verbose_name='Şrift (Məs: Inter, Poppins)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='product',
            name='navbar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/logos/', verbose_name='Xüsusi Navbar Loqosu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_cta_link',
            field=models.CharField(default='#pricing', max_length=200, verbose_name='İkinci düymə linki'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_cta_text',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, verbose_name='İkinci düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_cta_text_az',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, null=True, verbose_name='İkinci düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_cta_text_en',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, null=True, verbose_name='İkinci düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_cta_text_ru',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, null=True, verbose_name='İkinci düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_cta_text_tr',
            field=models.CharField(default='Qiymətlərə Bax', max_length=100, null=True, verbose_name='İkinci düymə mətni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Altbaşlıq'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle_az',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Altbaşlıq'),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme_color',
            field=models.CharField(default='blue', max_length=50, verbose_name='Mövzu rəngi (Məs: blue, emerald)'),
        ),
        migrations.AlterField(
            model_name='productbenefit',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='İkon (Məs: FaCheckCircle)'),
        ),
        migrations.AlterField(
            model_name='productbenefit',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='productbenefit',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productbenefit',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productbenefit',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productbenefit',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productbenefit',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='İkon (Məs: FaBolt)'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='productnavbarlink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='features',
            field=models.TextField(verbose_name='Xüsusiyyətlər (hər sətirə bir dənə)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='features_az',
            field=models.TextField(null=True, verbose_name='Xüsusiyyətlər (hər sətirə bir dənə)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='features_en',
            field=models.TextField(null=True, verbose_name='Xüsusiyyətlər (hər sətirə bir dənə)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='features_ru',
            field=models.TextField(null=True, verbose_name='Xüsusiyyətlər (hər sətirə bir dənə)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='features_tr',
            field=models.TextField(null=True, verbose_name='Xüsusiyyətlər (hər sətirə bir dənə)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Ən çox seçiləndir?'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Paket adı'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='name_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Paket adı'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Paket adı'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Paket adı'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Paket adı'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Müddət (Məs: /aylıq)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='period_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Müddət (Məs: /aylıq)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='period_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Müddət (Məs: /aylıq)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='period_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Müddət (Məs: /aylıq)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='period_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Müddət (Məs: /aylıq)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Qiymət (Məs: 99₼)'),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Başlıq (Məs: Aktiv İstifadəçi)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='label_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq (Məs: Aktiv İstifadəçi)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='label_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq (Məs: Aktiv İstifadəçi)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='label_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq (Məs: Aktiv İstifadəçi)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='label_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq (Məs: Aktiv İstifadəçi)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Rəqəm (Məs: 10K+)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='value_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Rəqəm (Məs: 10K+)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Rəqəm (Məs: 10K+)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='value_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Rəqəm (Məs: 10K+)'),
        ),
        migrations.AlterField(
            model_name='productstat',
            name='value_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='Rəqəm (Məs: 10K+)'),
        ),
    ]
