# Generated by Django 6.0.2 on 2026-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=50, unique=True, verbose_name='İzləmə kodu')),
                ('client_name', models.CharField(max_length=200, verbose_name='Müştəri')),
                ('project_name', models.CharField(max_length=200, verbose_name='Layihə adı')),
                ('current_step', models.CharField(max_length=100, verbose_name='Cari mərhələ')),
                ('current_step_az', models.CharField(max_length=100, null=True, verbose_name='Cari mərhələ')),
                ('current_step_en', models.CharField(max_length=100, null=True, verbose_name='Cari mərhələ')),
                ('current_step_ru', models.CharField(max_length=100, null=True, verbose_name='Cari mərhələ')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Proqres (%)')),
                ('status_note', models.TextField(blank=True, verbose_name='Vəziyyət qeydi')),
                ('status_note_az', models.TextField(blank=True, null=True, verbose_name='Vəziyyət qeydi')),
                ('status_note_en', models.TextField(blank=True, null=True, verbose_name='Vəziyyət qeydi')),
                ('status_note_ru', models.TextField(blank=True, null=True, verbose_name='Vəziyyət qeydi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('steps_data', models.JSONField(default=list, help_text="Mərhələlərin siyahısı: [{'name': '...', 'completed': true/false/'active'}]")),
            ],
            options={
                'verbose_name': 'Layihə İzləmə',
                'verbose_name_plural': 'Layihə İzləmələri',
            },
        ),
    ]
