# Generated by Django 6.0.2 on 2026-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_ordertracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='current_step_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Cari mərhələ'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='status_note_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Vəziyyət qeydi'),
        ),
    ]
