# Generated by Django 6.0.2 on 2026-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Qısa təsvir')),
                ('description_az', models.TextField(null=True, verbose_name='Qısa təsvir')),
                ('description_en', models.TextField(null=True, verbose_name='Qısa təsvir')),
                ('description_ru', models.TextField(null=True, verbose_name='Qısa təsvir')),
                ('icon_name', models.CharField(help_text='React-icon adı (məs: FaCode)', max_length=100, verbose_name='İkon')),
                ('content', models.TextField(help_text='Daxili səhifə üçün', verbose_name='Ətraflı məzmun')),
                ('content_az', models.TextField(help_text='Daxili səhifə üçün', null=True, verbose_name='Ətraflı məzmun')),
                ('content_en', models.TextField(help_text='Daxili səhifə üçün', null=True, verbose_name='Ətraflı məzmun')),
                ('content_ru', models.TextField(help_text='Daxili səhifə üçün', null=True, verbose_name='Ətraflı məzmun')),
                ('price', models.CharField(max_length=100, verbose_name='Qiymət')),
                ('price_az', models.CharField(max_length=100, null=True, verbose_name='Qiymət')),
                ('price_en', models.CharField(max_length=100, null=True, verbose_name='Qiymət')),
                ('price_ru', models.CharField(max_length=100, null=True, verbose_name='Qiymət')),
                ('duration', models.CharField(max_length=100, verbose_name='Müddət')),
                ('duration_az', models.CharField(max_length=100, null=True, verbose_name='Müddət')),
                ('duration_en', models.CharField(max_length=100, null=True, verbose_name='Müddət')),
                ('duration_ru', models.CharField(max_length=100, null=True, verbose_name='Müddət')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ana səhifədə göstər?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['order'],
            },
        ),
    ]
