# Generated by Django 6.0.2 on 2026-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deliverables',
            field=models.TextField(blank=True, help_text='Hər bir maddəni yeni sətirdən yazın', verbose_name='Nələr daxildir (bir sətirdə bir)'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_az',
            field=models.TextField(blank=True, help_text='Hər bir maddəni yeni sətirdən yazın', null=True, verbose_name='Nələr daxildir (bir sətirdə bir)'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_en',
            field=models.TextField(blank=True, help_text='Hər bir maddəni yeni sətirdən yazın', null=True, verbose_name='Nələr daxildir (bir sətirdə bir)'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_ru',
            field=models.TextField(blank=True, help_text='Hər bir maddəni yeni sətirdən yazın', null=True, verbose_name='Nələr daxildir (bir sətirdə bir)'),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_stack',
            field=models.TextField(blank=True, help_text='Məs: React, NestJS, MongoDB', verbose_name='Texnologiya steki (vergüllə ayrılmış)'),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_stack_az',
            field=models.TextField(blank=True, help_text='Məs: React, NestJS, MongoDB', null=True, verbose_name='Texnologiya steki (vergüllə ayrılmış)'),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_stack_en',
            field=models.TextField(blank=True, help_text='Məs: React, NestJS, MongoDB', null=True, verbose_name='Texnologiya steki (vergüllə ayrılmış)'),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_stack_ru',
            field=models.TextField(blank=True, help_text='Məs: React, NestJS, MongoDB', null=True, verbose_name='Texnologiya steki (vergüllə ayrılmış)'),
        ),
    ]
