# Generated by Django 6.0.2 on 2026-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content_tr',
            field=models.TextField(help_text='Daxili səhifə üçün', null=True, verbose_name='Ətraflı məzmun'),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables_tr',
            field=models.TextField(blank=True, help_text='Hər bir maddəni yeni sətirdən yazın', null=True, verbose_name='Nələr daxildir (bir sətirdə bir)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Qısa təsvir'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Müddət'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Qiymət'),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_stack_tr',
            field=models.TextField(blank=True, help_text='Məs: React, NestJS, MongoDB', null=True, verbose_name='Texnologiya steki (vergüllə ayrılmış)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
    ]
