# Generated by Django 6.0.2 on 2026-07-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_content_tr_service_deliverables_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug_az',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_tr',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
