# Generated by Django 6.0.2 on 2026-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('text_az', models.CharField(max_length=255, null=True)),
                ('text_en', models.CharField(max_length=255, null=True)),
                ('text_ru', models.CharField(max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CRM Üstünlüyü',
                'verbose_name_plural': 'CRM Üstünlükləri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CRMFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_az', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('icon_name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CRM Xüsusiyyəti',
                'verbose_name_plural': 'CRM Xüsusiyyətləri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CRMPricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_az', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('subtitle_az', models.CharField(max_length=200, null=True)),
                ('subtitle_en', models.CharField(max_length=200, null=True)),
                ('subtitle_ru', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=50)),
                ('period', models.CharField(default='₼/ay', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('cta_text', models.CharField(default='Başla', max_length=50)),
                ('cta_text_az', models.CharField(default='Başla', max_length=50, null=True)),
                ('cta_text_en', models.CharField(default='Başla', max_length=50, null=True)),
                ('cta_text_ru', models.CharField(default='Başla', max_length=50, null=True)),
                ('features', models.JSONField(help_text='Xüsusiyyətlər siyahısı (JSON formatında)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CRM Qiymət Paketi',
                'verbose_name_plural': 'CRM Qiymət Paketləri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CRMStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_percentage', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('label_az', models.CharField(max_length=100, null=True)),
                ('label_en', models.CharField(max_length=100, null=True)),
                ('label_ru', models.CharField(max_length=100, null=True)),
                ('school_count', models.CharField(max_length=50)),
                ('student_count', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CRM Statistika',
                'verbose_name_plural': 'CRM Statistikaları',
            },
        ),
    ]
