# Generated by Django 6.0.2 on 2026-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_crmbenefit_id_alter_crmfeature_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='12:00:00', max_length=100)),
                ('type', models.CharField(max_length=100, verbose_name='Log Tipi')),
                ('text', models.TextField(verbose_name='Log Məzmunu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CRM Bildirişi / Log',
                'verbose_name_plural': 'CRM Bildirişləri / Loglar',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='crmbenefit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crmfeature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crmpricingplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crmstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
