# Generated by Django 6.0.2 on 2026-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactinfo_id_alter_contactmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
