# Generated by Django 6.0.2 on 2026-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactinfo_address_tr_contactinfo_working_hours_tr'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalReachStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_name_az', models.CharField(max_length=100, null=True)),
                ('country_name_en', models.CharField(max_length=100, null=True)),
                ('country_name_ru', models.CharField(max_length=100, null=True)),
                ('country_name_tr', models.CharField(max_length=100, null=True)),
                ('client_count', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Qlobal Fəaliyyət Statistikası',
                'verbose_name_plural': 'Qlobal Fəaliyyət Statistikaları',
                'ordering': ['order'],
            },
        ),
    ]
