# Generated by Django 6.0.2 on 2026-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(max_length=100)),
                ('badge_text_az', models.CharField(max_length=100, null=True)),
                ('badge_text_en', models.CharField(max_length=100, null=True)),
                ('badge_text_ru', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Qlobal CTA',
                'verbose_name_plural': 'Qlobal CTA',
            },
        ),
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('quote', models.TextField()),
                ('quote_az', models.TextField(null=True)),
                ('quote_en', models.TextField(null=True)),
                ('quote_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Ana Səhifə Haqqında',
                'verbose_name_plural': 'Ana Səhifə Haqqında',
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(max_length=100)),
                ('badge_text_az', models.CharField(max_length=100, null=True)),
                ('badge_text_en', models.CharField(max_length=100, null=True)),
                ('badge_text_ru', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(help_text='Məs: Biznesinizi <span>gücləndirən</span> texniki həllər', max_length=255)),
                ('title_az', models.CharField(help_text='Məs: Biznesinizi <span>gücləndirən</span> texniki həllər', max_length=255, null=True)),
                ('title_en', models.CharField(help_text='Məs: Biznesinizi <span>gücləndirən</span> texniki həllər', max_length=255, null=True)),
                ('title_ru', models.CharField(help_text='Məs: Biznesinizi <span>gücləndirən</span> texniki həllər', max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('hero_image', models.ImageField(upload_to='home/')),
            ],
            options={
                'verbose_name': 'Ana Səhifə Hero',
                'verbose_name_plural': 'Ana Səhifə Hero',
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('label_az', models.CharField(max_length=100, null=True)),
                ('label_en', models.CharField(max_length=100, null=True)),
                ('label_ru', models.CharField(max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ana Səhifə Statistika',
                'verbose_name_plural': 'Ana Səhifə Statistikaları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('title_az', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('duration', models.CharField(max_length=100)),
                ('duration_az', models.CharField(max_length=100, null=True)),
                ('duration_en', models.CharField(max_length=100, null=True)),
                ('duration_ru', models.CharField(max_length=100, null=True)),
                ('deliverables', models.JSONField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'İş Prosesi Mərhələsi',
                'verbose_name_plural': 'İş Prosesi Mərhələləri',
                'ordering': ['order'],
            },
        ),
    ]
