# Generated by Django 5.1.3 on 2026-03-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Partnyor Adı')),
                ('name_az', models.CharField(max_length=200, null=True, verbose_name='Partnyor Adı')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Partnyor Adı')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Partnyor Adı')),
                ('industry', models.CharField(max_length=150, verbose_name='Sektor')),
                ('industry_az', models.CharField(max_length=150, null=True, verbose_name='Sektor')),
                ('industry_en', models.CharField(max_length=150, null=True, verbose_name='Sektor')),
                ('industry_ru', models.CharField(max_length=150, null=True, verbose_name='Sektor')),
                ('description', models.TextField(verbose_name='Qısa Təsvir')),
                ('description_az', models.TextField(null=True, verbose_name='Qısa Təsvir')),
                ('description_en', models.TextField(null=True, verbose_name='Qısa Təsvir')),
                ('description_ru', models.TextField(null=True, verbose_name='Qısa Təsvir')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Loqo Şəkli')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Vebsayt')),
                ('since_year', models.CharField(default='2020', max_length=4, verbose_name='Əməkdaşlıq İlə')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Partnyor/Brend',
                'verbose_name_plural': 'Partnyorlar və Brendlər',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='globalcta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workprocessstep',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
