# Generated by Django 6.0.2 on 2026-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_globalcta_id_alter_homeabout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcta',
            name='badge_text_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='globalcta',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='globalcta',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='quote_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='badge_text_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homehero',
            name='title_tr',
            field=models.CharField(help_text='Məs: Biznesinizi <span>gücləndirən</span> texniki həllər', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homestat',
            name='label_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Qısa Təsvir'),
        ),
        migrations.AddField(
            model_name='partner',
            name='industry_tr',
            field=models.CharField(max_length=150, null=True, verbose_name='Sektor'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Partnyor Adı'),
        ),
        migrations.AddField(
            model_name='workprocessstep',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workprocessstep',
            name='duration_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workprocessstep',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
